#pragma once
#include <string>

const std::string VERSION = "0.0.1";
const std::string DOC     = "USIC DOCUMENT:\n"
                            "Server:\n"
                            "  usic [FLAG]\n"
                            "  usic                  Run server\n"
                            "Available FLAG:\n"
                            "  -h, --help            Print this document\n"
                            "  -v, --version         Print version\n"
                            "\n"
                            "Tools:\n"
                            "  usic <COMMAND> [ARGUMENT]\n"
                            "Available COMMANDS:\n"
                            "  add_music_to_list     Add music to playlist        REQUIRED ARGUMENT: "
                            "The name of playlist\n"
                            "\n"
                            "Client:\n"
                            "  usic <COMMAND> [ARGUMENT]\n"
                            "Available COMMANDS:\n"
                            "  load                  Load playlist                REQUIRED ARGUMENT: "
                            "The name of playlist\n"
                            "  play                  Play music                   OPTIONAL ARGUMENT: "
                            "The path of music file; play the first in playlist if not provided\n"
                            "  play_later            Play given music next        REQUIRED ARGUMENT: "
                            "The path of music file\n"
                            "  play_next             Play next music in playlist  NO ARGUMENT\n"
                            "  play_prev             Play previous music          NO ARGUMENT\n"
                            "  pause                 Pause or resume music        NO ARGUMENT\n"
                            "  cursor_forward        Move cursor forward          NO ARGUMENT\n"
                            "  cursor_backward       Move cursor backward         NO ARGUMENT\n"
                            "  set_cursor            Set cursor to given time     REQUIRED ARGUMENT: "
                            "Time in MM:SS format\n"
                            "  get_current_progress  Get current progress         NO ARGUMENT\n"
                            "  volume_up             Increase volume              NO ARGUMENT\n"
                            "  volume_down           Decrease volume              NO ARGUMENT\n"
                            "  set_volume            Set volume                   REQUIRED ARGUMENT: "
                            "Volume between 0.0 and 1.0\n"
                            "  get_volume            Get current volume           NO ARGUMENT\n"
                            "  mute                  Mute or unmute volume        NO ARGUMENT\n"
                            "  set_random            Toggle random mode           NO ARGUMENT\n"
                            "  set_repetitive        Toggle repetitive mode       NO ARGUMENT\n"
                            "  get_list              Print playlist               NO ARGUMENT\n"
                            "  quit                  Quit server                  NO ARGUMENT\n";
